- name: directory
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0700
  with_items:
    - "{{ ansible_user_dir }}/.ssh"

- name: authorized_keys
  lineinfile:
    path: "{{ ansible_user_dir }}/.ssh/authorized_keys"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600
    regexp: "{{ item.type | regex_escape }} {{ item.public_key | regex_escape }}"
    line: "{% if item.options is defined %}{{ item.options }}{% endif %}{{ item.type }} {{ item.public_key }} {{ item.comment }}"
  with_items:
    - "{{ ssh_public_key_setup_list }}"

# Local Variables:
# indent-tabs-mode: nil
# End:
