- hosts: all
  roles:
    - login_umask
    - wsl_apt_preferences
    - apt_packages
    - python_packages
    - sshd_authpass
    - sshd_host_keys
    - ssh_public_key
    - emacs_d
    - dotfiles
    - pandoc_github_css
    - xfonts
    - y10k.ruby_build
    - y10k.rubygems_setup
  tasks:
    - include_role:
        name: y10k.kelleyk_emacs
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == 20
    - include_role:
        name: emacs
      when: not(ansible_distribution == "Ubuntu" and ansible_distribution_major_version == 20)

# Local Variables:
# indent-tabs-mode: nil
# End:
