- hosts: all
  roles:
    - login_umask
    - wsl_apt_preferences
    - desktop_packages
    - sshd_authpass
    - y10k.ruby_build
    - ruby-system-gems

# Local Variables:
# indent-tabs-mode: nil
# End:
