- hosts: all
  roles:
    - login_umask
    - wsl_apt_preferences
    - desktop_packages
    - python_packages
    - sshd_authpass
    - y10k.kelleyk_emacs
    - xfonts
    - y10k.ruby_build
    - y10k.rubygems_setup

# Local Variables:
# indent-tabs-mode: nil
# End:
