- hosts: all
  roles:
    - login_umask
    - wsl_apt_preferences
    - emacs26_install
    - desktop_packages
    - sshd_authpass
    # - qdbm_symlinks
    - xfonts
    - y10k.ruby_build
    - y10k.rubygems_setup
    # - y10k.rubygems_update

# Local Variables:
# indent-tabs-mode: nil
# End:
