- name: git clone
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: no
  with_items:
    - repo: "{{ dotfiles_git_repo }}"
      dest: "{{ dotfiles_user_dir }}/{{ dotfiles_git_clone_name }}"

- name: check state
  fail:
    msg: not allowed state
  with_items: >-
    {{ dotfiles_link_list | rejectattr("state", "in", ("present", "absent")) |  list }}

- name: absent links
  file:
    state: absent
    path: "{{ dotfiles_user_dir }}/{{ item.path }}"
  with_items: >-
    {{ dotfiles_link_list | selectattr("state", "eq", "absent") | list }}

- name: present links
  file:
    state: link
    path: "{{ dotfiles_user_dir }}/{{ item.path }}"
    src: "./{{ dotfiles_git_clone_name }}/{{ item.src }}"
    force: yes
  with_items: >-
    {{ dotfiles_link_list | selectattr("state", "eq", "present") | list }}

# Local Variables:
# indent-tabs-mode: nil
# End:
