- name: QDBM symbolic links
  become: yes
  file:
    state: link
    path: "/usr/include/{{ item }}"
    src: "/usr/include/qdbm/{{ item }}"
  with_items:
    - cabin.h
    - curia.h
    - depot.h
    - odeum.h
    - relic.h
    - villa.h
    - vista.h

# Local Variables:
# indent-tabs-mode: nil
# End:
