- name: check setup state
  fail:
    msg: not allowed state
  with_items: >-
    {{ apt_packages_setup_list | rejectattr("state", "in", ("present", "absent")) |  list }}

- name: absent packages
  become: yes
  apt:
    name: >-
      {{ apt_packages_setup_list | selectattr("state", "eq", "absent") | map(attribute="name") | list }}
    state: absent
    purge: yes

- name: present packages
  become: yes
  apt:
    name: >-
      {{ apt_packages_setup_list | selectattr("state", "eq", "present") | map(attribute="name") | list }}
    state: present

# Local Variables:
# indent-tabs-mode: nil
# End:
