- name: check setup state
  fail:
    msg: not allowed state
  with_items: >-
    {{ desktop_packages_setup_list | selectattr("state", "ne", "absent") | selectattr("state", "ne", "present") | list }}

- name: absent packages
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: >-
    {{ desktop_packages_setup_list | selectattr("state", "eq", "absent") | map(attribute="name") | list }}

- name: present packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: >-
    {{ desktop_packages_setup_list | selectattr("state", "eq", "present") | map(attribute="name") | list }}

# Local Variables:
# indent-tabs-mode: nil
# End:
